-- =====================================================
-- REVENUE BY COUNTRY
-- Purpose: Total revenue generated by each country
-- Business question: Which markets are most profitable?
-- =====================================================

SELECT 
    c.country,
    COUNT(DISTINCT c.customer_id) AS total_customers,
    COUNT(o.order_id) AS total_orders,
    ROUND(SUM(o.total_amount), 2) AS total_revenue,
    ROUND(AVG(o.total_amount), 2) AS avg_order_value
FROM tables.customers c
JOIN tables.orders o ON c.customer_id = o.customer_id
WHERE o.status = 'Delivered'  -- Only completed orders
GROUP BY c.country
ORDER BY total_revenue DESC;
